Update thameera-swagger_pr-ai-dev_app_84a80ed_env_0b5e21b.yaml

diff --git a/.github/workflows/thameera-swagger_pr-ai-dev_app_84a80ed_env_0b5e21b.yaml b/.github/workflows/thameera-swagger_pr-ai-dev_app_84a80ed_env_0b5e21b.yaml
--- a/.github/workflows/thameera-swagger_pr-ai-dev_app_84a80ed_env_0b5e21b.yaml
+++ b/.github/workflows/thameera-swagger_pr-ai-dev_app_84a80ed_env_0b5e21b.yaml
@@ -136,16 +136,37 @@ jobs:
                     echo "###########################################################"
                     echo $task_id
                     echo "###########################################################"
-                    
-                    status_code=$?
-                    if [ $status_code -eq 0 ]; then
-                      echo "SUCCESS :: $response"
-                      identifiedFiles=$(echo "$response" | jq -r '.identified_files')
-                    echo "identified-files=$identifiedFiles" >> $GITHUB_OUTPUT
+                    if [ -n "$task_id" ]; then
+                      echo "Task ID: $task_id"
+            
+                      while true; do
+                        final_response=$(curl -X GET -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-auth-by: sa' -H 'x-organization-id: ${{ env.PIPELINE_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.PIPELINE_PROJECT_ID }}' -H 'x-trace-id: ${{ env.PIPELINE_TRACE_ID }}' -H 'x-resource-id: ${{ env.PIPELINE_APPLICATION_ID }}' -H 'Content-Type: application/json'  "${{ env.AI_SUGGESTED_SOLUTION_EP }}/identify-files/$task_id")
+                        echo "Task Status Response: $final_response"
+                        task_status=$(echo "$final_response" | jq -r '.status')
+            
+                        if [ "$task_status" != "completed" ]; then
+                        echo "Task processing ..."
+                        sleep 10  
+                        else
+                          echo "Task done... Proceeding"
+                          break
+                        fi
+                      done
+            
+                      status_code=$?
+                      if [ $status_code -eq 0 ]; then
+                        echo "SUCCESS :: $final_response"
+                        identifiedFiles=$(echo "$final_response" | jq -r '.result' | jq -r '.identified_files')
+                      echo "identified-files=$identifiedFiles" >> $GITHUB_OUTPUT
+                      else
+                        echo "FAILED :: $response"
+                        exit 1
+                      fi
                     else
-                      echo "FAILED :: $response"
+                      echo "Failed to Start Task"
                       exit 1
                     fi
+
                     
       - name: 'Run :: Create new branch'
         run: git checkout -b fix-issue-${{ github.run_id }}
